"""empty message

Revision ID: a0110d41c3d9
Revises: 213e8399d011
Create Date: 2025-06-26 12:50:39.071849

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a0110d41c3d9"
down_revision = "213e8399d011"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "log",
        "is_active",
        existing_type=sa.INTEGER(),
        type_=sa.Boolean(),
        existing_nullable=False,
    )
    op.add_column("user", sa.Column("created_by", sa.Integer(), nullable=True))
    op.add_column("user", sa.Column("updated_by", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "user", "user", ["created_by"], ["id"])
    op.create_foreign_key(None, "user", "user", ["updated_by"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("", "user", type_="foreignkey")
    op.drop_constraint("", "user", type_="foreignkey")
    op.drop_column("user", "updated_by")
    op.drop_column("user", "created_by")
    op.alter_column(
        "log",
        "is_active",
        existing_type=sa.Boolean(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
