services:
  api:
    ports:
      - "8000:8000"
    build:
      context: .
    volumes:
      - .:/app
    environment:
      API_RELOAD: "True"
    networks:
      - local

  db:
    ports:
      - "5432:5432"
    networks:
      - local

networks:
  local:
    external: true
